apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: dbsecret
 labels: 
  app: dbapp
spec:
    replicas: 2
    
    selector:
      matchLabels:
       app: dbapp

    template:

       metadata:
         labels:
          app: dbapp

       spec:
         containers:
          - name : dbapp
            image: mysql:latest
            ports:
             - containerPort: 3306
            env:
              - name: MYSQL_ROOT_Password
                valueFrom:
                 secretKeyRef:
                  name: dbsecret
                  key: dbkey


