apiVersion: apps/v1

kind: Deployment

metadata:
  name: deploy
  labels:
    app: app-deploy

spec:
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    selector:
      matchLabels:
        app: app-deploy
    template:
      metadata:
        labels:
          app: app-deploy
      spec:
        containers:
          - name: nginx
            image: nginx:latest
            ports:
             - containerPort: 80


